version: '3.3'
# Anya i love you!
services: 
  lb:
    image: jfahrer/lb:v3
    ports: 
      - "80:80"
    depends_on: 
      - webapp
    environment: 
      - PROXY_UPSTREAM
  pg:
    image: postgres:9.6-alpine
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes: 
      - pg-data:/var/lib/postgresql/data
  
  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    depends_on: 
      - pg
    ports: 
      - "9292:9292"
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
volumes:
  pg-data:
